# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: This action will send PR to slack
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Slack - code review
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "Codeowners": "U123456789",
              "Summary": "${{ github.event.pull_request.title }}",
              "URL": "${{ github.event.pull_request._links.self.href }}"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/triggers/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
